name: smartage_care
description: Allow users to find out real-time status of the elderly after installing the SmartAge package in their houses.
publish_to: 'none'
version: 1.1.1+1


environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  flutter_native_splash: ^2.0.0

  # drop shadow for image
  drop_shadow_image: ^0.9.0
  
  # add the SQLite and path dependency.
  path: ^1.8.3  
  sqflite: ^2.0.0+4

  # format DateTime
  intl: ^0.19.0

  # display todos in grid
  flutter_staggered_grid_view: ^0.7.0
  ## -- STATE MANAGEMENT
  get: ^4.6.5

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.66.0
  path_provider: ^2.1.0
  simple_shadow: ^0.3.1
  flutter_switch: ^0.3.2
  shared_preferences: ^2.2.3
  zoom_widget: ^2.0.1
  image_picker: ^1.0.0


  # Firebase
  cloud_firestore: ^4.13.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_core_platform_interface: ^5.0.0
  firebase_database: ^10.3.0
  firebase_messaging: ^14.7.0
  firebase_storage: ^11.2.5
  google_sign_in: ^6.0.0
  
  
  # Notification
  uuid: ^4.0.0
  fluttertoast: ^8.2.2
  flutter_plugin_android_lifecycle: ^2.0.15
  flutter_local_notifications:  ^17.2.1

  http: ^1.1.0
  stroke_text: ^0.0.2
  flutter_svg: ^2.0.7

  # Language Support
  slang: ^3.28.0
  slang_flutter: ^3.28.0
  flutter_localization: ^0.2.0
  google_fonts: 6.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/smartage_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/images/characters/
    - assets/images/health/
    - assets/images/profile/
    - assets/images/activity/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/db/elderlyDB.db

  # fonts:
  #   - family: AppIcons
  #     fonts:
  #       - asset: assets/fonts/Temperature.ttf
  #       - asset: assets/fonts/Poppins-Regular.ttf
