/*
  This is an auto-generated file by Firebase CLI. Please do not edit or move this file
*/

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        debugPrint('Android');
        return android;
      case TargetPlatform.iOS:
        debugPrint('iOS');
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIloQz9cAISLzXS1rSJSjya_dINavC58',
    appId: '1:920895648172:web:af27d1f90afdd601de8a09',
    messagingSenderId: '920895648172',
    projectId: 'smartage-31839',
    authDomain: 'smartage-31839.firebaseapp.com',
    databaseURL:
        'https://smartage-31839-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartage-31839.appspot.com',
    measurementId: 'G-PRFNRZP05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUi5DHzhqhH1_sjGtERclGyQHIZ1IqSFk',
    appId: '1:920895648172:android:5f47b3e423041ca5de8a09',
    messagingSenderId: '920895648172',
    projectId: 'smartage-31839',
    databaseURL:
        'https://smartage-31839-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartage-31839.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUi5DHzhqhH1_sjGtERclGyQHIZ1IqSFk',
    appId: '1:920895648172:ios:0bca1a010c2cfda4de8a09',
    messagingSenderId: '920895648172',
    projectId: 'smartage-31839',
    databaseURL:
        'https://smartage-31839-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartage-31839.appspot.com',
    iosClientId:
        '920895648172-3hmat1jo30tfqbcq0jakm6er5a8svrrt.apps.googleusercontent.com',
    iosBundleId: 'com.Sanways.SmartAge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2DHIeiPpZcEBcNq8BlPE5CcZdvSaCFos',
    appId: '1:920895648172:ios:2ee58af82122a8d0de8a09',
    messagingSenderId: '920895648172',
    projectId: 'smartage-31839',
    databaseURL:
        'https://smartage-31839-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartage-31839.appspot.com',
    iosClientId:
        '920895648172-r2kfqpkn752358g3kfmlqv4dapr9n87h.apps.googleusercontent.com',
    iosBundleId: 'com.example.refactoredSmartAgeFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWIloQz9cAISLzXS1rSJSjya_dINavC58',
    appId: '1:920895648172:web:54cb657b88cadb3fde8a09',
    messagingSenderId: '920895648172',
    projectId: 'smartage-31839',
    authDomain: 'smartage-31839.firebaseapp.com',
    databaseURL:
        'https://smartage-31839-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartage-31839.appspot.com',
    measurementId: 'G-PG5DWV0WXM',
  );
}
